version: '2'
services:
    poupapplication-app:
        image: poupapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://poupapplication-mysql:3306/poupapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    poupapplication-mysql:
        extends:
            file: mysql.yml
            service: poupapplication-mysql
